In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2025-01-21 06:03:29.075651: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-21 06:03:31.095858: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-21 06:03:32.088128: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1737419613.150758    5674 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1737419613.396852    5674 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-21 06:03:36.017412: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU ins

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2000, 9467, 3143, 8321],
 [2000, 9467, 3143, 8943],
 [2000, 5752, 3143, 6247],
 [3420, 9263, 940, 3334, 8753],
 [3420, 9263, 940, 3334, 4490],
 [9424, 2000, 3324, 3143, 2423],
 [1967, 8200, 8411, 3334]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2000 9467 3143 8321]
 [   0    0    0    0 2000 9467 3143 8943]
 [   0    0    0    0 2000 5752 3143 6247]
 [   0    0    0 3420 9263  940 3334 8753]
 [   0    0    0 3420 9263  940 3334 4490]
 [   0    0    0 9424 2000 3324 3143 2423]
 [   0    0    0    0 1967 8200 8411 3334]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/home/vpsr/.local/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2025-01-21 06:08:33.874569: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


array([[[ 1.37107112e-02,  1.43046863e-02,  3.98006923e-02,
          4.41766493e-02,  1.89087875e-02,  2.44319327e-02,
         -2.93429941e-03, -4.27718423e-02,  2.06258409e-02,
         -2.15173252e-02],
        [ 1.37107112e-02,  1.43046863e-02,  3.98006923e-02,
          4.41766493e-02,  1.89087875e-02,  2.44319327e-02,
         -2.93429941e-03, -4.27718423e-02,  2.06258409e-02,
         -2.15173252e-02],
        [ 1.37107112e-02,  1.43046863e-02,  3.98006923e-02,
          4.41766493e-02,  1.89087875e-02,  2.44319327e-02,
         -2.93429941e-03, -4.27718423e-02,  2.06258409e-02,
         -2.15173252e-02],
        [ 1.37107112e-02,  1.43046863e-02,  3.98006923e-02,
          4.41766493e-02,  1.89087875e-02,  2.44319327e-02,
         -2.93429941e-03, -4.27718423e-02,  2.06258409e-02,
         -2.15173252e-02],
        [-4.21032533e-02,  3.19096334e-02,  3.60236280e-02,
          4.57835458e-02,  1.49099343e-02,  1.32349469e-02,
          3.83916982e-02, -4.66708094e-03,  2.622269